[colors]
background = '#eff1f5'
compose_cursor = '#dd7878'
cursor_bg = '#dc8a78'
cursor_border = '#dc8a78'
cursor_fg = '#dce0e8'
foreground = '#4c4f69'
scrollbar_thumb = '#acb0be'
selection_bg = '#acb0be'
selection_fg = '#4c4f69'
split = '#9ca0b0'
visual_bell = '#ccd0da'

ansi = [
  '#bcc0cc',
  '#d20f39',
  '#40a02b',
  '#df8e1d',
  '#1e66f5',
  '#ea76cb',
  '#179299',
  '#5c5f77',
]
brights = [
  '#acb0be',
  '#d20f39',
  '#40a02b',
  '#df8e1d',
  '#1e66f5',
  '#ea76cb',
  '#179299',
  '#6c6f85',
]
