# Set mouse mode on

set -g mouse on

# Set focus event (nvim)
set-option -g focus-events on

# status bar
# Status bar
set -g status on
set -g status-position bottom
bind-key b set-option status

# Status bar styling
set -g status-style bg=#000000,fg=#d9c447
set -g status-left "#S"
set -g status-right "Panel:#P"

# Windows in the middle
set -g status-justify centre
set -g window-status-format "#[fg=#c4c4c4]#I:#W"
set -g window-status-current-format "#I:#W"

# Set copy mode
bind v copy-mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Delay after prefix
set -sg escape-time 0

# Set true colors compatibility
set -g default-terminal "tmux-256color"
set -sa terminal-overrides ',*:RGB'

# Create new window current path
bind-key c command-prompt -p "Insert name:" "new-window -c '#{pane_current_path}' -n '%%'"

# Split vertical panel in current path
bind-key - split-window -c "#{pane_current_path}"
bind-key '"' split-window -c "~"

bind-key | split-window -h -c "#{pane_current_path}"
bind-key % split-window -h -c "~"

# Display panel numbers time
set -g display-panes-time 10000

# Remove kill panel confirmation 
bind-key x kill-pane

# Base index
set -g base-index 1
set -g pane-base-index 1

# Panel border type
set -g pane-border-lines simple

# Terminal history limit
set-option -g history-limit 5000

# Resize pane by 1 cell
bind-key -r ^ last-window
bind-key -r j resize-pane -D
bind-key -r k resize-pane -U 
bind-key -r h resize-pane -L 
bind-key -r l resize-pane -R 

# Yazi configuration
set -g allow-passthrough on
set -ga update-environment TERM

# Bind go to the previous panel
bind O select-pane -t :.-

bind -r t neww -c "#{pane_current_path}" \
"(cd ~/Documents/github/notes && nvim todo.md)"

bind-key P run-shell ~/bin/global/tmux/tmux-remove-panels
bind-key W run-shell ~/bin/global/tmux/tmux-remove-windows

bind-key K run-shell "~/bin/global/tmux/tmux-remove-all github"
bind-key C run-shell "~/bin/global/tmux/tmux-remove-all bryant"

bind-key D run-shell "\
~/bin/global/tmux/tmux-new-session /home/bryant/Documents/github/dotfiles/"

bind-key H run-shell "~/bin/global/tmux/tmux-new-session /home/bryant/"

bind-key Y run-shell "~/bin/global/tmux/tmux-new-session \
/home/bryant/Documents/github/youtube"

bind-key N run-shell "~/bin/global/tmux/tmux-new-session \
/home/bryant/Documents/github/nvim"

bind-key G run-shell "~/bin/global/tmux/tmux-new-session \
/home/bryant/Documents/github"

bind-key S run-shell "tmux neww ~/bin/global/tmux/tmux-new-session"

bind-key I run-shell "tmux neww ~/bin/global/tmux/tmux-cht"

bind-key T run-shell "tmux neww ~/bin/global/tmux/tmux-translate"

# TMUX NAVIGATOR
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# Reload tmux configuration
bind r source-file ~/.tmux.conf \; display-message "tmux reloaded."
