# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# set mouse mode on
set -g mouse on

# set focus event (nvim)
set-option -g focus-events on

# status bar styling
set -g status-style bg=#000000,fg=#d9c447
set -g status-left "#S"
set -g status-right "Panel:#P"

# windows in the middle
set -g status-justify centre
set -g window-status-format "#[fg=#c4c4c4]#I:#W"
set -g window-status-current-format "#I:#W"

# base index
set -g base-index 1
set -g pane-base-index 1

# panel border type
set -g pane-border-lines simple

# terminal history limit
set-option -g history-limit 5000

# Status bar
set -g status on
set -g status-position bottom

# delay after prefix
set -sg escape-time 0

# set true colors compatibility
set -g default-terminal "tmux-256color"
set -sa terminal-overrides ',*:RGB'

# yazi configuration
set -g allow-passthrough on
set -ga update-environment TERM

# toggle status bar
bind-key b set-option status

# set copy mode like neovim
bind-key v copy-mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# create new window current path
bind-key c command-prompt \
-p "Insert name:" "new-window -c '#{pane_current_path}' -n '%%'"

# split vertical panel in current path
bind-key '"' split-window -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"

# display panel numbers time
set -g display-panes-time 10000

# remove kill panel confirmation
bind-key x kill-pane

# resize pane by 1 cell
bind-key -r J resize-pane -D
bind-key -r K resize-pane -U
bind-key -r H resize-pane -L
bind-key -r L resize-pane -R

# tmux default key bind remaps
bind-key s switch-client -l
bind-key S choose-session
bind-key N next-window
bind-key P previous-window


# tmux script, open directories as a sessions
bind-key C run-shell "~/bin/global/tmux/tmux-remove-all bryant"

bind-key d run-shell "\
~/bin/global/tmux/tmux-new-session /home/bryant/Documents/github/dotfiles/"

bind-key h run-shell "~/bin/global/tmux/tmux-new-session /home/bryant/"

bind-key y run-shell "~/bin/global/tmux/tmux-new-session \
/home/bryant/Documents/github/youtube"

# open todo.md notes in current directories or in notes folder
bind-key -r t neww -c "#{pane_current_path}" \
"(cd ~/Documents/github/notes && nvim todo.md)"

# tmux scripts, new open window with some script in it
bind-key i run-shell "tmux neww ~/bin/global/tmux/tmux-cht"
bind-key e run-shell "tmux neww ~/bin/global/tmux/tmux-translate"
bind-key u run-shell "tmux neww ~/bin/global/tmux/tmux-new-session"


# TMUX NAVIGATOR
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# Reload tmux configuration
bind-key R source-file ~/.tmux.conf \; display-message "Updated configuration"
