# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# set mouse mode on
set -g mouse on

# set focus event (nvim)
set-option -g focus-events on

# NOTE: status bar style
set -g status-left-length '50'
set -g status-right-length '50'
set -g status-justify 'absolute-centre'
set -g status-style 'bg=#000000,fg=red'

# right side
set -g status-left '#S#[fg=gray]#{S:#{?session_attached,, #S}}'

# center
set -g window-status-current-format '#I:'
set -g window-status-format '#[fg=gray]#I:'

# left side
set -g status-right 'Panel: #P'

# base index
set -g base-index 1
set -g pane-base-index 1

# panel border type
set -g pane-border-lines simple

# terminal history limit
set-option -g history-limit 5000

# Status bar
set -g status on
set -g status-position bottom

# delay after prefix
set -sg escape-time 0

# set true colors compatibility
set -sa terminal-overrides ',*:RGB'
set -g default-terminal "tmux-256color"

# yazi configuration
set -g visual-activity off
set -g allow-passthrough on
set -ga update-environment TERM

# display panel numbers time
set -g display-panes-time 10000

# WARN: FROM HERE THE DEFAULT TMUX `BIND-KEY` WILL BE OVERWRITTEN

# set copy mode like neovim
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim-like pane switching
bind-key ^ last-window
bind-key k select-pane -U
bind-key j select-pane -D
bind-key h select-pane -L
bind-key l select-pane -R

# toggle status bar
bind-key b set-option status

# create new window current path
bind-key c "new-window -c '#{pane_current_path}'"

# split vertical and horizontal panel in current tmux panel path
bind-key '"' split-window -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"

# open my todo
bind-key t neww -c "#{pane_current_path}" "(cd ~/Documents/github/notes && nvim todo.md)"

# switch directories
bind-key H run-shell "~/bin/tmux/tmux-new-session /home/bryant/"
bind-key G run-shell "~/bin/tmux/tmux-new-session /home/bryant/Documents/github"
bind-key N run-shell "~/bin/tmux/tmux-new-session /home/bryant/Documents/github/notes"
bind-key Y run-shell "~/bin/tmux/tmux-new-session /home/bryant/Documents/github/youtube"
bind-key D run-shell "~/bin/tmux/tmux-new-session /home/bryant/Documents/github/dotfiles"

# custom scripts for better default tmux bind-keys
bind-key x run-shell "~/bin/tmux/tmux-close-window"
bind-key s run-shell "~/bin/tmux/tmux-switch-session"
bind-key K run-shell "~/bin/tmux/tmux-remove-all bryant"

# custom scripts for translation, search commands and session management
bind-key i run-shell "tmux neww ~/bin/tmux/tmux-cht"
bind-key e run-shell "tmux neww ~/bin/tmux/tmux-translate"
bind-key u run-shell "tmux neww ~/bin/tmux/tmux-new-session"
bind-key a run-shell "tmux neww ~/bin/tmux/tmux-select-session"

# refresh tmux client with message
bind-key r run-shell "tmux refresh-client && tmux display-message 'Client refreshed!'"
# Reload tmux configuration
bind-key R source-file ~/.tmux.conf \; display-message "Updated configuration"
