live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#3d353b"
blue = "#75a7b3"
cyan = "#70a9a1"
green = "#b1a1d1"
magenta = "#b58da6"
red = "#d4969c"
white = "#b9a2bf"
yellow = "#e9cdd0"

[colors.cursor]
cursor = "#c7aed6"
text = "#3d353b"

[colors.dim]
black = "#3e353b"
blue = "#75a7b3"
cyan = "#70a9a1"
green = "#b1a1d1"
magenta = "#b58da6"
red = "#d4969c"
white = "#b9a2bf"
yellow = "#e9cdd0"

[colors.normal]
black = "#2a273f"
blue = "#75a7b3"
cyan = "#70a9a1"
green = "#b1a1d1"
magenta = "#b58da6"
red = "#d4969c"
white = "#c5bdd2"
yellow = "#e9cdd0"

[colors.primary]
background = "#191724"
dim_foreground = "#c5bdd2"
foreground = "#c7aed6"

[colors.search.matches]
background = "#70a9a1"
foreground = "#3e353b"

[colors.selection]
background = "#3d353b"
text = "#b9a2bf"

[colors.vi_mode_cursor]
cursor = "#c7aed6"
text = "#3d353b"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "Maple Mono NF"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF"
style = "Bold"

[font.italic]
family = "Maple Mono NF"
style = "Regular"

[font.normal]
family = "Maple Mono NF"
style = "Bold"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[mouse]
hide_when_typing = true

[window]
decorations = "full"
dynamic_padding = true
opacity = 1
startup_mode = "Windowed"
