live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#393552"
blue = "#3e8fb0"
cyan = "#9ccfd8"
green = "#f6c177"
magenta = "#c4a7e7"
red = "#eb6f92"
white = "#908caa"
yellow = "#ea9a97"

[colors.cursor]
cursor = "#e0def4"
text = "#232136"

[colors.dim]
black = "#2a273f"
blue = "#3e8fb0"
cyan = "#9ccfd8"
green = "#f6c177"
magenta = "#c4a7e7"
red = "#eb6f92"
white = "#6e6a86"
yellow = "#ea9a97"

[colors.normal]
black = "#312E3D"
blue = "#3e8fb0"
cyan = "#9ccfd8"
green = "#f6c177"
magenta = "#c4a7e7"
red = "#eb6f92"
white = "#ECEBF0"
yellow = "#ea9a97"

[colors.primary]
background = "#191724"
dim_foreground = "#ECEBF0"
foreground = "#e0def4"

[colors.search.matches]
background = "#9ccfd8"
foreground = "CellBackground"

[colors.selection]
background = "#393552"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#e0def4"
text = "#232136"

[cursor.style]
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "Maple Mono NF"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF"
style = "Bold"

[font.italic]
family = "Maple Mono NF"
style = "Regular"

[font.normal]
family = "Maple Mono NF"
style = "Bold"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[mouse]
hide_when_typing = true

[window]
decorations = "full"
dynamic_padding = true
opacity = 1
startup_mode = "Windowed"
