db_path = "~/.history.db"

filter_mode = "host" # session/global/directory

key_path = "~/.key"

session_path = "~/.session"

dialect = "us"

style = "compact"

inline_height = 10

auto_sync = true

update_check = true

sync_address = "https://api.atuin.sh"

sync_frequency = "1h"

history_filter = [
  "^clear",
  "^z"
]

cwd_filter = [
  "^/very/secret/area"
]

max_preview_height = 4

show_help = true

secrets_filter = true

enter_accept = true

common_subcommands = [
 "cargo",
 "go",
 "git",
 "npm",
 "yarn",
 "pnpm",
 "kubectl",
]
# 
common_prefix = ["sudo"]

keymap_mode = "vim-normal"

keymap_cursor = { vim_insert = "steady-underline", vim_normal = "steady-underline" }
