#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config window_gap 1
bspc config top_padding 0
bspc config border_width 3
bspc config split_ratio 0.50
bspc config bottom_padding 0
bspc config gapless_monocle false
bspc config borderless_monocle false
bspc config focus_follows_pointer false
bspc config focused_border_color "#757575"

# app favorite desktop
bspc rule -a Postman desktop=^4 follow=off
bspc rule -a bruno desktop=^4 follow=off

bspc rule -a calibre desktop=^7 follow=off
bspc rule -a Gimp-3.0 desktop=^7 follow=off
bspc rule -a obsidian desktop=^7 follow=off
bspc rule -a qBittorrent desktop=^7 follow=off

bspc rule -a vesktop desktop=^8 follow=off


# app favorite mode
bspc rule -a pavucontrol state=floating center=true

xset s off -dpms &
xsetroot -cursor_name left_ptr & # fix mouse

~/.fehbg &
~/bin/wm/toggle_polybar &

pgrep -x "picom" >/dev/null || picom &
pgrep -x "dunst" >/dev/null || dunst &
pgrep -x "udiskie" >/dev/null || udiskie &
pgrep -x "sxhkd" >/dev/null || sxhkd -m -1 &
pgrep -x "unclutter" >/dev/null || unclutter &
