#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config top_padding 0
bspc config bottom_padding 14
bspc config border_width 2

bspc config focused_border_color "#aa759f"

bspc config split_ratio 0.50

bspc config gapless_monocle false
bspc config borderless_monocle false

bspc config window_gap 0

bspc config focus_follows_pointer false

# app favorite desktop
bspc rule -a Postman desktop=^4 follow=off
bspc rule -a obsidian desktop=^9 follow=off
bspc rule -a qBittorrent desktop=^10 follow=off

# app favorite mode
bspc rule -a pavucontrol state=floating center=true

xset s off -dpms &
xsetroot -cursor_name left_ptr & # fix mouse

~/.fehbg &
~/bin/wm/start_polybar &

pgrep -x "picom" >/dev/null || picom &
pgrep -x "udiskie" >/dev/null || udiskie &
pgrep -x "unclutter" >/dev/null || unclutter &
pgrep -x "sxhkd" >/dev/null || sxhkd -m -1 &
