[metadata]
aliases = []
author = 'chatgpt'
name = 'alacritty'

[colors]
background = '#181818'
compose_cursor = '#cc6666'
cursor_bg = '#b5bd68'
cursor_border = '#b5bd68'
cursor_fg = '#c5c8c6'
foreground = '#c5c8c6'
scrollbar_thumb = '#666666'
selection_bg = '#666666'
selection_fg = '#c5c8c6'
split = '#d54e53'
visual_bell = '#b5bd68'

ansi = [
  '#1d1f21',  # Black
  '#cc6666',  # Red
  '#b5bd68',  # Green
  '#f0c674',  # Yellow
  '#81a2be',  # Blue
  '#b294bb',  # Magenta
  '#8abeb7',  # Cyan
  '#c5c8c6',  # White
]

brights = [
  '#666666',  # Bright Black
  '#d54e53',  # Bright Red
  '#b9ca4a',  # Bright Green
  '#e7c547',  # Bright Yellow
  '#7aa6da',  # Bright Blue
  '#c397d8',  # Bright Magenta
  '#70c0b1',  # Bright Cyan
  '#eaeaea',  # Bright White
]

[colors.indexed]
16 = '#862d59'
17 = '#c5c8c6'

[colors.tab_bar]
background = '#181818'
inactive_tab_edge = '#c5c8c6'

[colors.tab_bar.active_tab]
bg_color = '#81a2be'
fg_color = '#c5c8c6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#1d1f21'
fg_color = '#c5c8c6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#181818'
fg_color = '#c5c8c6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#c5c8c6'
fg_color = '#1d1f21'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#666666'
fg_color = '#c5c8c6'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'
