[general]
live_config_reload = true

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10.5

[font.normal]
family = "Recursive Mn Csl St Smb"

[font.bold]
family = "Recursive Mn Csl St Smb"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "!"
mods = "Control"

[mouse]
hide_when_typing = true

[window]
opacity = 0.9
dynamic_padding = true
padding = { x = 0, y = 0 }


[colors]
[colors.primary]
background = "#1d1f21"
foreground = "#ffffff"

[colors.cursor]
text = "#1d1f21"
cursor = "#957139"

[colors.normal]
black = "#1d1f21"
red = "#cc6666"
green = "#b5bd68"
yellow = "#f0c674"
blue = "#81a2be"
magenta = "#b294bb"
cyan = "#8abeb7"
white = "#c5c8c6"

[colors.bright]
black = "#666666"
red = "#d54e53"
green = "#b9ca4a"
yellow = "#e7c547"
blue = "#7aa6da"
magenta = "#c397d8"
cyan = "#70c0b1"
white = "#eaeaea"
