"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[line_break]
disabled = true

[character]                            
success_symbol = "[](green bold)"     
error_symbol = "[!](green bold)"
vimcmd_symbol = "[](green bold)"

[git_branch]
format = "[$branch]($style) "

[git_status]
disabled = true
