add_newline = false

format = """
$directory\
$character"""

# Directory configuration
[directory]
truncation_length = 2
truncate_to_repo = false
style = "white"

[character]
success_symbol = "[󰁕](#55392c)"
error_symbol = "[✗](#55392c)"
