display-name = "Bryant Paz"
downloads-dir = "~/Documents/himalaya/"
signature = "Atentament,\nBryant Paz"
email-listing-page-size = 25


[microsoft-main]
default = true
email = "plbryant@hotmail.com"

backend = "imap"
imap-host = "outlook.office365.com"
imap-port = 993
imap-login = "plbryant@hotmail.com"

imap-auth="passwd"
imap-passwd.cmd = "pass show himalaya/microsoft/main"

sender = "smtp"
smtp-host = "smtp-mail.outlook.com"
smtp-port = 587
smtp-starttls = true
smtp-login = "plbryant@hotmail.com"

smtp-auth="passwd"
smtp-passwd.cmd = "pass show himalaya/microsoft/main"


[microsoft-work]
email = "plbryantt@outlook.com"

backend = "imap"
imap-host = "outlook.office365.com"
imap-port = 993
imap-login = "plbryantt@outlook.com"

imap-auth="passwd"
imap-passwd.cmd = "pass show himalaya/microsoft/work"

sender = "smtp"
smtp-host = "smtp-mail.outlook.com"
smtp-port = 587
smtp-starttls = true
smtp-login = "plbryantt@outlook.com"

smtp-auth="passwd"
smtp-passwd.cmd = "pass show himalaya/microsoft/work"



[google-main]
email = "pazitaa117@gmail.com"

backend = "imap"
imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "pazitaa117@gmail.com"

imap-auth="passwd"
imap-passwd.cmd = "pass show himalaya/google/main"

sender = "smtp"
smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "pazitaa117@gmail.com"

smtp-auth="passwd"
smtp-passwd.cmd = "pass show himalaya/google/main"

[google-main.folder-aliases]
inbox = "INBOX"
sent = "[Gmail]/Sent Mail"
drafts = "[Gmail]/Drafts"
trash = "[Gmail]/Trash"
