add_newline = false

[line_break]
disabled = true

[directory]
truncation_length = 2

[character]                            
success_symbol = "[](bold)"     
error_symbol = "[!](bold)"
vimcmd_symbol = "[](bold)"

[git_branch]
format = "[$branch]($style)"

[git_status]
disabled = true
