add_newline = false

[line_break]
disabled = true

[directory]
truncation_length = 2

[character]                            
success_symbol = "[](bold green)"     
error_symbol = "[!](bold red)"
vimcmd_symbol = "[](bold yellow)"
