add_newline = false

[line_break]
disabled = true

[directory]
truncation_length = 1

[character]                            
success_symbol = "[](bold green)"     
error_symbol = "[!](bold red)"
vimcmd_symbol = "[](bold yellow)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
disabled = true
