# THIS IS EXPERIMENTAL
# the config file schema may change at any time

style:
  tag:
    color: cyan # text color. possible values: https://bit.ly/3gloNNI
    width_percentage: 26 # column width relative to the terminal window
    min_width: 20 # minimum column width as number of characters
  comment:
    color: blue
    width_percentage: 42
    min_width: 100
  snippet:
    color: white

client:
  tealdeer: true # enables tealdeer support for navi --tldr

finder:
  command: skim # equivalent to the --finder option

shell:
  command: zsh
